({ type = "ai",		file = "ai.xls",		sheet= "怪物实体数据", },
{ index = "id",		value = "int",		desc = "怪物ID编号", },
{ field = "atkType",		value = "int",		desc = "主动/被动", },
{ field = "isSkill",		value = "int",		desc = "主动技能", },
{ field = "look",		value = "int",		desc = "视野范围(象素)", },
{ field = "selectType",		value = "string",		desc = "选取类型", },
{ field = "chaserange",		value = "int",		desc = "追击范围(象素)", },
{ field = "script",		value = "string",		desc = "脚本", },
{ field = "point",		value = "string",		desc = "寻路点", },
)

({ type = "buffs",		file = "buffs.xls",		sheet= "Sheet1", },
{ index = "id",		value = "int",		desc = "状态ID", },
{ field = "name",		value = "string",		desc = "状态名", },
{ field = "description",		value = "string",		desc = "状态描述", },
{ field = "stateIcon",		value = "int",		desc = "状态图标", },
{ field = "cartoonId",		value = "int",		desc = "状态动画", },
{ field = "effId",		value = "string",		desc = "状态特效", },
{ field = "playMode",		value = "int",		desc = "特效播放方式", },
{ field = "conflictId",		value = "string",		desc = "状态互斥大类ID", },
{ field = "typeId",		value = "int",		desc = "状态类型ID", },
{ field = "lv",		value = "int",		desc = "状态等级", },
{ field = "stateType",		value = "int",		desc = "状态类型", },
{ field = "canAdd",		value = "int",		desc = "是否替换", },
{ field = "addCount",		value = "int",		desc = "最大叠加数", },
{ field = "beforePk",		value = "string",		desc = "前置事件", },
{ field = "attribute",		value = "string",		desc = "对应属性项", },
{ field = "endPk",		value = "string",		desc = "后置事件", },
{ field = "pkEnd",		value = "string",		desc = "pk结束后运行,只运行释放者", },
{ field = "buffTime",		value = "int",		desc = "持续时间", },
{ field = "buffCount",		value = "int",		desc = "生效次数", },
{ field = "breakTime",		value = "int",		desc = "运行时间间隔(秒)", },
{ field = "dissed",		value = "int",		desc = "能否驱散", },
{ field = "disremo",		value = "int",		desc = "能否清除", },
{ field = "reset",		value = "int",		desc = "重置清除", },
{ field = "isTeamBuff",		value = "int",		desc = "是否在状态栏显示buff图标", },
{ field = "music",		value = "string",		desc = "音效", },
)

({ type = "consume",		file = "item.xls",		sheet= "消耗品", },
{ index = "itemId",		value = "int",		desc = "物品id", },
{ field = "name",		value = "string",		desc = "名字", },
{ field = "remark",		value = "string",		desc = "描述", },
{ field = "lv",		value = "int",		desc = "使用等级", },
{ field = "useRemark",		value = "string",		desc = "使用描述", },
{ field = "outPrice",		value = "int",		desc = "卖出价格", },
{ field = "useType",		value = "int",		desc = "可否背包使用", },
{ field = "useLimit",		value = "int",		desc = "职业限制", },
{ field = "binding",		value = "int",		desc = "绑定类型（0=拾取绑定，2=装备绑定，1=未绑定）", },
{ field = "usearea",		value = "int",		desc = "使用范围（0无限制,1背包,2战斗中,3副本,4兽骨）", },
{ field = "canAdd",		value = "int",		desc = "是否可叠加 0可,1不可", },
{ field = "img",		value = "int",		desc = "使用图标", },
{ field = "categoryI",		value = "int",		desc = "一级类别（1 消耗品 2 装备 3 卷轴 4 灵魂石 5.英雄整卡 ）", },
{ field = "categoryII",		value = "int",		desc = "二级类别(101扫荡卷、102附魔粉、103经验药、104兑换金币、105英雄整卡、106体力药、107神秘入场卷、108头像框、109钻石、110战队经验、111刀锋币、112斗士币、113VIP体验卡114礼包115钻石10连抽卷、115联盟币116肉盾材料卡117输出材料卡118辅助材料卡119体力值1回复能量120宝箱类物品121英雄雕像122转生材料123皮肤道具、124精华碎片、125英雄碎片、126和平勋章、127月卡、128升阶材料、129修炼材料)", },
{ field = "color",		value = "int",		desc = "颜色(0白、1绿、2蓝、3紫、4橙、5灰、6红)", },
{ field = "orderId",		value = "int",		desc = "排序ID", },
{ field = "colour",		value = "string",		desc = "皮肤", },
{ field = "isRemark",		value = "int",		desc = "是否请求描述", },
{ field = "itemSource",		value = "string",		desc = "精华字段", },
{ field = "fumoExp",		value = "int",		desc = "附魔经验", },
{ field = "heroExp",		value = "int",		desc = "英雄经验", },
{ field = "null",		value = "string",		desc = "来源描述", },
{ field = "star",		value = "int",		desc = "星级", },
{ field = "type",		value = "int",		desc = "类别", },
{ field = "null",		value = "string",		desc = "碎片使用", },
)

({ type = "dailyTask",		file = "tasks.xls",		sheet= "每日任务", },
{ index = "taskId",		value = "int",		desc = "任务id", },
{ field = "name",		value = "string",		desc = "任务名称", },
{ field = "desc",		value = "string",		desc = "任务描述", },
{ field = "icon",		value = "int",		desc = "任务图标", },
{ field = "type",		value = "int",		desc = "类型(0:剧情任务,1:每日任务)", },
{ field = "rewardExpr",		value = "string",		desc = "任务奖励", },
{ field = "order",		value = "int",		desc = "任务顺序排列", },
{ field = "limitCAmout",		value = "int",		desc = "活动限制完成次数（单位天）", },
{ field = "null",		value = "string",		desc = "前往", },
)

({ type = "enterSpine",		file = "enterSpine.xls",		sheet= "主城动画", },
{ index = "id",		value = "int",		desc = "int", },
{ field = "文件名",		value = "string",		desc = "string", },
{ field = "缩放X",		value = "int",		desc = "int", },
{ field = "缩放Y",		value = "int",		desc = "int", },
{ field = "x(正右负左)",		value = "int",		desc = "int", },
{ field = "y(正下负上)",		value = "int",		desc = "int", },
)

({ type = "equip",		file = "item.xls",		sheet= "装备", },
{ index = "itemId",		value = "int",		desc = "物品id", },
{ field = "name",		value = "string",		desc = "名字", },
{ field = "useLimit",		value = "int",		desc = "职业限制", },
{ field = "remark",		value = "string",		desc = "描述", },
{ field = "lv",		value = "int",		desc = "使用等级", },
{ field = "useRemark",		value = "string",		desc = "属性描述", },
{ field = "outPrice",		value = "int",		desc = "卖出价格", },
{ field = "binding",		value = "int",		desc = "绑定类型（0=拾取绑定,2=装备绑定,1=未绑定）", },
{ field = "usearea",		value = "int",		desc = "使用范围（0无限制,1背包,2战斗中,3副本,4兽骨）", },
{ field = "canAdd",		value = "int",		desc = "是否可叠加 0可,1不可", },
{ field = "img",		value = "int",		desc = "图标", },
{ field = "attribute",		value = "string",		desc = "功能字串", },
{ field = "addFumoAttr",		value = "string",		desc = "附魔基本属性", },
{ field = "color",		value = "int",		desc = "颜色(0白、1绿、2蓝、3紫、4橙 5红、6金)", },
{ field = "orderId",		value = "int",		desc = "排序ID", },
{ field = "colour",		value = "string",		desc = "颜色码", },
{ field = "isRemark",		value = "int",		desc = "是否请求描述", },
{ field = "position",		value = "int",		desc = "装备部位", },
{ field = "star",		value = "int",		desc = "装备星级", },
{ field = "suitId",		value = "int",		desc = "套装编号", },
{ field = "haloExp",		value = "int",		desc = "光环经验", },
)

({ type = "equipmentSuit",		file = "equipmentSuit.xls",		sheet= "套装", },
{ index = "id",		value = "int",		desc = "套装ID", },
{ field = "name",		value = "string",		desc = "套装名", },
{ field = "effectDesc",		value = "string",		desc = "套装效果描述", },
{ field = "effect",		value = "string",		desc = "套装效果", },
)

({ type = "exp",		file = "exp.xls",		sheet= "等级消耗返还", },
{ index = "lv",		value = "int",		desc = "等级", },
{ field = "heroExp",		value = "int",		desc = "英雄升级所需经验", },
{ field = "teamExp",		value = "int",		desc = "团队升级所需经验", },
{ field = "rewardPower",		value = "int",		desc = "奖励体力", },
{ field = "equipForgeMoney",		value = "int",		desc = "装备锻造升级金钱", },
)

({ type = "fightProfile",		file = "fightProfile.xls",		sheet= "Sheet1", },
{ index = "id",		value = "int",		desc = "id", },
{ field = "typeId",		value = "int",		desc = "类型id", },
{ field = "childId",		value = "int",		desc = "子项id", },
{ field = "name",		value = "string",		desc = "评测项目名称", },
{ field = "lvStr",		value = "string",		desc = "评测等级划分", },
{ field = "jumpToUi",		value = "string",		desc = "跳转ui", },
{ field = "checkStr",		value = "string",		desc = "评级规则", },
)

({ type = "guanka_chapter",		file = "chapter.xls",		sheet= "chapter", },
{ index = "id",		value = "int",		desc = "章节ID", },
{ field = "name",		value = "string",		desc = "章节名字", },
{ field = "remark",		value = "string",		desc = "章节序数", },
{ field = "sceneId",		value = "int",		desc = "场景ID", },
{ field = "preId",		value = "int",		desc = "前一章节ID", },
{ field = "nextId",		value = "int",		desc = "后一章节ID", },
{ field = "resId",		value = "int",		desc = "底图", },
{ field = "null",		value = "int",		desc = "关卡形象", },
{ field = "lv",		value = "int",		desc = "开放等级", },
{ field = "chapterId",		value = "int",		desc = "前置章节", },
{ field = "achieveId",		value = "string",		desc = "特定成就ID", },
{ field = "photoId",		value = "int",		desc = "章节标题icon", },
{ field = "difficulty",		value = "int",		desc = "难度", },
{ field = "typeId",		value = "int",		desc = "章节大类Id", },
{ field = "",		value = "string",		desc = "章节UI名字", },
{ field = "",		value = "string",		desc = "章数", },
{ field = "xy",		value = "string",		desc = "坐标", },
)

({ type = "guanka_level",		file = "chapter.xls",		sheet= "guan", },
{ index = "id",		value = "int",		desc = "关卡ID", },
{ field = "name",		value = "string",		desc = "关卡名", },
{ field = "remark",		value = "string",		desc = "关卡描述", },
{ field = "open",		value = "int",		desc = "是否默认开放", },
{ field = "lv",		value = "int",		desc = "难度等级", },
{ field = "chapterId",		value = "int",		desc = "章节ID", },
{ field = "openLv",		value = "int",		desc = "开启等级", },
{ field = "guanId",		value = "int",		desc = "前置关卡Id", },
{ field = "preId",		value = "int",		desc = "前一关卡的ID", },
{ field = "nextId",		value = "int",		desc = "后一关卡的ID", },
{ field = "power",		value = "int",		desc = "消耗体力值", },
{ field = "losePower",		value = "int",		desc = "失败扣的体力值", },
{ field = "maps",		value = "string",		desc = "地图数据", },
{ field = "mons",		value = "string",		desc = "怪物id", },
{ field = "prices",		value = "string",		desc = "奖励展示", },
{ field = "photoId",		value = "int",		desc = "关卡标题icon", },
{ field = "teamExp",		value = "int",		desc = "战队经验", },
{ field = "heroExp",		value = "int",		desc = "英雄经验", },
{ field = "loseExp",		value = "int",		desc = "失败经验", },
{ field = "money",		value = "int",		desc = "金币掉落", },
{ field = "guanType",		value = "int",		desc = "关卡类型", },
{ field = "monsterShow",		value = "string",		desc = "怪物展示", },
{ field = "null",		value = "string",		desc = "地图行走区域", },
{ field = "null",		value = "string",		desc = "脚本 物件", },
{ field = "null",		value = "string",		desc = "客户端脚本", },
{ field = "null",		value = "int",		desc = "图标", },
{ field = "null",		value = "int",		desc = "推荐等级", },
{ field = "bgMusic",		value = "string",		desc = "关卡背景音乐", },
{ field = "notice",		value = "string",		desc = "关卡提示", },
{ field = "",		value = "string",		desc = "剧情对白", },
{ field = "",		value = "string",		desc = "关卡后剧情对白", },
{ field = "",		value = "string",		desc = "全局怪", },
{ field = "power",		value = "int",		desc = "能量初始值", },
{ field = "",		value = "string",		desc = "BOSS出现资源", },
)

({ type = "guanka_scene",		file = "chapter.xls",		sheet= "scene", },
{ index = "id",		value = "int",		desc = "场景ID", },
{ field = "null",		value = "string",		desc = "场景名字", },
{ field = "type",		value = "int",		desc = "章节类型", },
{ field = "null",		value = "int",		desc = "前一场景ID", },
{ field = "null",		value = "int",		desc = "后一场景ID", },
{ field = "null",		value = "int",		desc = "标题图", },
{ field = "null",		value = "int",		desc = "底图", },
)

({ type = "guideUi",		file = "guideUi.xls",		sheet= "Sheet1", },
{ index = "id",		value = "int",		desc = "id", },
{ field = "typeId",		value = "int",		desc = "类型id", },
{ field = "step",		value = "int",		desc = "步数step", },
{ field = "clickStep",		value = "int",		desc = "执行保存", },
{ field = "returnStep",		value = "int",		desc = "如果中断,则跳去指定步骤", },
{ field = "skipStep",		value = "int",		desc = "跳过后续几步", },
{ field = "isEnd",		value = "int",		desc = "是否终止所有ui引导", },
{ field = "isDiglog",		value = "int",		desc = "是否大白对话", },
{ field = "isShow",		value = "int",		desc = "触发方式", },
{ field = "fileName",		value = "string",		desc = "文件名layout", },
{ field = "widgetName",		value = "string",		desc = "控件名widgetName", },
{ field = "rootName",		value = "string",		desc = "listBox父控件root", },
{ field = "childName",		value = "string",		desc = "listBox对应列控件名", },
{ field = "index",		value = "int",		desc = "listBox下标", },
{ field = "delay",		value = "int",		desc = "延迟显示", },
{ field = "imageId",		value = "int",		desc = "图片资源", },
{ field = "effectId",		value = "int",		desc = "特效资源", },
{ field = "spineId",		value = "int",		desc = "spine资源", },
{ field = "x",		value = "int",		desc = "提示坐标x", },
{ field = "y",		value = "int",		desc = "提示坐标y", },
{ field = "btnX",		value = "int",		desc = "响应控件坐标x", },
{ field = "btnY",		value = "int",		desc = "响应控件坐标y", },
{ field = "name",		value = "string",		desc = "头像名字", },
{ field = "text",		value = "string",		desc = "提示文字", },
)

({ type = "guideUiS",		file = "guideUiS.xls",		sheet= "Sheet1", },
{ index = "id",		value = "int",		desc = "id", },
{ field = "typeId",		value = "int",		desc = "类型id", },
{ field = "step",		value = "int",		desc = "步数step", },
{ field = "clickStep",		value = "int",		desc = "执行保存", },
{ field = "returnStep",		value = "int",		desc = "如果中断,则跳去指定步骤", },
{ field = "skipStep",		value = "int",		desc = "跳过后续几步", },
{ field = "isEnd",		value = "int",		desc = "是否终止ui引导", },
{ field = "isDiglog",		value = "int",		desc = "是否大白对话", },
{ field = "showType",		value = "string",		desc = "触发方式", },
{ field = "isShowFinger",		value = "int",		desc = "是否显示手指", },
{ field = "isShowDamper",		value = "int",		desc = "是否显示黑色挡板", },
{ field = "isJumpUi",		value = "int",		desc = "结束是否跳转ui", },
{ field = "fileName",		value = "string",		desc = "文件名layout", },
{ field = "widgetName",		value = "string",		desc = "控件名widgetName", },
{ field = "rootName",		value = "string",		desc = "listBox父控件root", },
{ field = "childName",		value = "string",		desc = "listBox对应列控件名", },
{ field = "index",		value = "int",		desc = "listBox下标", },
{ field = "delay",		value = "int",		desc = "延迟显示", },
{ field = "imageId",		value = "int",		desc = "图片资源", },
{ field = "effectId",		value = "int",		desc = "特效资源", },
{ field = "spineId",		value = "int",		desc = "spine资源", },
{ field = "x",		value = "int",		desc = "提示坐标x", },
{ field = "y",		value = "int",		desc = "提示坐标y", },
{ field = "btnX",		value = "int",		desc = "响应控件坐标x", },
{ field = "btnY",		value = "int",		desc = "响应控件坐标y", },
{ field = "name",		value = "string",		desc = "头像名字", },
{ field = "text",		value = "string",		desc = "提示文字", },
)

({ type = "hero",		file = "hero.xls",		sheet= "怪物实体数据", },
{ index = "id",		value = "int",		desc = "卡牌ID编号", },
{ field = "type",		value = "int",		desc = "类别", },
{ field = "function",		value = "string",		desc = "方法", },
{ field = "name",		value = "string",		desc = "名称", },
{ field = "description",		value = "string",		desc = "卡牌描述", },
{ field = "animationId",		value = "int",		desc = "角色资源ID", },
{ field = "photoId",		value = "int",		desc = "背包头像ID", },
{ field = "atktype",		value = "int",		desc = "怪物的攻击方式(0近攻，1远攻）", },
{ field = "moveSpeed",		value = "int",		desc = "移动速度", },
{ field = "attackSpeed",		value = "int",		desc = "攻击速度(200毫秒的倍数)", },
{ field = "phyAct",		value = "int",		desc = "物理攻击", },
{ field = "phyIgnore",		value = "int",		desc = "物理穿透", },
{ field = "phyDef",		value = "int",		desc = "物理护甲值", },
{ field = "magicIgnore",		value = "int",		desc = "法术穿透", },
{ field = "magicDef",		value = "int",		desc = "魔法抗性值", },
{ field = "cri",		value = "int",		desc = "暴击", },
{ field = "maxHp",		value = "int",		desc = "生命值", },
{ field = "maxMp",		value = "int",		desc = "能量值", },
{ field = "mpRecover",		value = "int",		desc = "能量恢复值", },
{ field = "dodge",		value = "int",		desc = "闪避", },
{ field = "skills",		value = "string",		desc = "技能池", },
{ field = "skillsSeq",		value = "string",		desc = "技能次序", },
{ field = "ai",		value = "string",		desc = "AI", },
{ field = "scale",		value = "int",		desc = "放缩", },
{ field = "star",		value = "int",		desc = "初始星级", },
{ field = "spineId2",		value = "string",		desc = "图鉴动画", },
{ field = "isOpen",		value = "int",		desc = "是否开放", },
{ field = "namePhotoId",		value = "int",		desc = "名称美术字", },
{ field = "0",		value = "int",		desc = "动画位置x", },
{ field = "0",		value = "int",		desc = "动画位置y", },
{ field = "110",		value = "int",		desc = "动画缩放", },
{ field = "dieMusic",		value = "string",		desc = "死亡音效", },
{ field = "null",		value = "int",		desc = "是否赠送", },
{ field = "jobico",		value = "int",		desc = "职业图标", },
{ field = "nameImgId",		value = "int",		desc = "抽奖名字", },
{ field = "tenacity",		value = "int",		desc = "韧性值", },
{ field = "hit",		value = "int",		desc = "命中值", },
{ field = "suckHp",		value = "int",		desc = "吸血%", },
{ field = "rebound",		value = "int",		desc = "反弹%", },
{ field = "srcHero",		value = "int",		desc = "原英雄", },
{ field = "fightIcon",		value = "int",		desc = "玩家头像", },
{ field = "energyIcon",		value = "string",		desc = "怒气头像", },
{ field = "partner",		value = "string",		desc = "连携伙伴和buff", },
{ field = "rebirthBuff",		value = "string",		desc = "转生buff", },
{ field = "rebirthBuffEff",		value = "string",		desc = "转生buff", },
{ field = "isValue",		value = "int",		desc = "是否珍稀", },
{ field = "intelligence",		value = "int",		desc = "资质", },
{ field = "gsFix",		value = "int",		desc = "战力系数", },
)

({ type = "heroTrain",		file = "heroTrain.xls",		sheet= "英雄修炼", },
{ index = "type",		value = "int",		desc = "类型", },
{ field = "lv",		value = "int",		desc = "等级", },
{ field = "attribute",		value = "string",		desc = "属性", },
{ field = "exp",		value = "int",		desc = "升级所需经验", },
)

({ type = "heroTrain2",		file = "heroTrain.xls",		sheet= "修炼加成", },
{ index = "lv",		value = "int",		desc = "两修炼等级", },
{ field = "attribute",		value = "string",		desc = "属性", },
)

({ type = "hollow",		file = "hollow.xls",		sheet= "沙巴克", },
{ index = "id",		value = "int",		desc = "据点ID", },
{ field = "type",		value = "int",		desc = "据点类型", },
{ field = "name",		value = "string",		desc = "据点名称", },
{ field = "relatePoints",		value = "string",		desc = "关联（周边）据点的集合", },
{ field = "settleAwards",		value = "string",		desc = "结算时下发的奖励", },
{ field = "icon",		value = "int",		desc = "据点图标资源", },
{ field = "relateroad",		value = "string",		desc = "关联路线", },
{ field = "text1",		value = "string",		desc = "占领", },
{ field = "text2",		value = "string",		desc = "占领奖励", },
{ field = "text3",		value = "string",		desc = "唯一BUFF", },
)

({ type = "monster",		file = "monster.xls",		sheet= "怪物实体数据", },
{ index = "id",		value = "int",		desc = "怪物ID编号", },
{ field = "typeII",		value = "int",		desc = "对象类别", },
{ field = "type",		value = "int",		desc = "类别", },
{ field = "function",		value = "string",		desc = "方法", },
{ field = "flag",		value = "int",		desc = "分类（程序用）", },
{ field = "name",		value = "string",		desc = "怪物名称", },
{ field = "description",		value = "string",		desc = "怪物描述", },
{ field = "photoId",		value = "int",		desc = "怪物头像ID", },
{ field = "animationId",		value = "int",		desc = "怪物资源ID", },
{ field = "lv",		value = "int",		desc = "怪物等级", },
{ field = "atktype",		value = "int",		desc = "怪物的攻击方式(0近攻，1远攻）", },
{ field = "phymp",		value = "int",		desc = "攻击类型0物攻/1法攻", },
{ field = "money",		value = "int",		desc = "击杀金钱", },
{ field = "exp",		value = "int",		desc = "击杀经验", },
{ field = "moveSpeed",		value = "int",		desc = "移动速度", },
{ field = "attackSpeed",		value = "int",		desc = "攻击速度(200毫秒的倍数)", },
{ field = "phyAct",		value = "int",		desc = "物理攻击", },
{ field = "phyIgnore",		value = "int",		desc = "物理穿透", },
{ field = "phyDef",		value = "int",		desc = "物理护甲值", },
{ field = "magicIgnore",		value = "int",		desc = "法术穿透", },
{ field = "magicDef",		value = "int",		desc = "魔法抗性值", },
{ field = "cri",		value = "int",		desc = "暴击率", },
{ field = "maxHp",		value = "int",		desc = "生命值", },
{ field = "hpRecover",		value = "int",		desc = "生命恢复值", },
{ field = "maxMp",		value = "int",		desc = "能量值", },
{ field = "mpRecover",		value = "int",		desc = "能量恢复值", },
{ field = "dodge",		value = "int",		desc = "闪避率", },
{ field = "skills",		value = "string",		desc = "技能池", },
{ field = "skillsSeq",		value = "string",		desc = "技能次序", },
{ field = "buff",		value = "string",		desc = "被动技能池", },
{ field = "ai",		value = "string",		desc = "AI", },
{ field = "droprule",		value = "string",		desc = "掉落规则", },
{ field = "effects",		value = "string",		desc = "特效id多个", },
{ field = "scale",		value = "int",		desc = "放缩", },
{ field = "layer",		value = "int",		desc = "层", },
{ field = "initdata",		value = "string",		desc = "初始化数据", },
{ field = "color",		value = "int",		desc = "怪物品阶", },
{ field = "boss",		value = "int",		desc = "是否BOSS", },
{ field = "null",		value = "string",		desc = "BOSS血条", },
{ field = "jobico",		value = "int",		desc = "职业图标", },
{ field = "tenacity",		value = "int",		desc = "韧性值", },
{ field = "hit",		value = "int",		desc = "命中值", },
{ field = "suckHp",		value = "int",		desc = "吸血%", },
{ field = "rebound",		value = "int",		desc = "反弹%", },
)

({ type = "newguideDialog",		file = "newguideDialog.xls",		sheet= "Sheet1", },
{ index = "id",		value = "int",		desc = "编号", },
{ field = "resId",		value = "string",		desc = "头像资源id", },
{ field = "heroId",		value = "int",		desc = "释放大招英雄id", },
{ field = "",		value = "int",		desc = "延迟时间", },
{ field = "side",		value = "int",		desc = "头像位置", },
{ field = "name",		value = "string",		desc = "角色名字", },
{ field = "dialog",		value = "string",		desc = "说话类容", },
)

({ type = "partner",		file = "partner.xls",		sheet= "星级阶数加成", },
{ index = "star",		value = "string",		desc = "星星_阶数", },
{ field = "buff",		value = "int",		desc = "加成的buffID", },
)

({ type = "plotTask",		file = "tasks.xls",		sheet= "剧情任务", },
{ index = "taskId",		value = "int",		desc = "任务id", },
{ field = "name",		value = "string",		desc = "任务名称", },
{ field = "desc",		value = "string",		desc = "任务描述", },
{ field = "icon",		value = "int",		desc = "任务图标", },
{ field = "type",		value = "int",		desc = "类型(0:剧情任务,1:每日任务)", },
{ field = "rewardExpr",		value = "string",		desc = "任务奖励", },
{ field = "order",		value = "int",		desc = "任务顺序排列", },
{ field = "limitCAmout",		value = "int",		desc = "活动限制完成次数（单位天）", },
{ field = "null",		value = "string",		desc = "前往", },
)

({ type = "pvp",		file = "pvp.xls",		sheet= "竞技场奖励", },
{ index = "rank",		value = "int",		desc = "排名", },
{ field = "reward",		value = "string",		desc = "奖励", },
)

({ type = "rebirth",		file = "rebirth.xls",		sheet= "Sheet1", },
{ index = "rebirthLv",		value = "int",		desc = "转生等级", },
{ field = "stuffStr",		value = "string",		desc = "所需材料", },
{ field = "hpAdd",		value = "int",		desc = "HP加成百分比", },
{ field = "attAdd",		value = "int",		desc = "ATT加成百分比", },
{ field = "extraBuff",		value = "int",		desc = "上阵小伙伴时的额外buff", },
{ field = "eff",		value = "int",		desc = "转生特效(废弃)", },
{ field = "stengthLimit",		value = "int",		desc = "阶数上限(废弃)", },
{ field = "luckLimit",		value = "int",		desc = "幸运值上限", },
{ field = "money",		value = "int",		desc = "消耗金币", },
{ field = "buffState",		value = "int",		desc = "转生光环", },
)

({ type = "rune",		file = "item.xls",		sheet= "符文", },
{ index = "itemId",		value = "int",		desc = "物品id", },
{ field = "name",		value = "string",		desc = "名字", },
{ field = "useLimit",		value = "int",		desc = "职业限制", },
{ field = "remark",		value = "string",		desc = "描述", },
{ field = "lv",		value = "int",		desc = "使用等级", },
{ field = "useRemark",		value = "string",		desc = "属性描述", },
{ field = "outPrice",		value = "int",		desc = "卖出价格", },
{ field = "binding",		value = "int",		desc = "绑定类型（0=拾取绑定,2=装备绑定,1=未绑定）", },
{ field = "usearea",		value = "int",		desc = "使用范围（0无限制,1背包,2战斗中,3副本,4兽骨）", },
{ field = "canAdd",		value = "int",		desc = "是否可叠加 0可,1不可", },
{ field = "img",		value = "int",		desc = "图标", },
{ field = "attribute",		value = "string",		desc = "功能字串", },
{ field = "addFumoAttr",		value = "string",		desc = "附魔基本属性", },
{ field = "color",		value = "int",		desc = "颜色(0白、1绿、2蓝、3紫、4橙 5红、6金)", },
{ field = "orderId",		value = "int",		desc = "排序ID", },
{ field = "colour",		value = "string",		desc = "颜色码", },
{ field = "isRemark",		value = "int",		desc = "是否请求描述", },
{ field = "categoryI",		value = "int",		desc = "一级类别（1 消耗品 2 装备 3 卷轴 4 灵魂石 5 符文 ）", },
{ field = "categoryII",		value = "int",		desc = "二级类别(201装备、202补偿装备、203符文、204精华、205精华碎片、206经验道具)", },
{ field = "position",		value = "int",		desc = "装备部位", },
{ field = "star",		value = "int",		desc = "装备星级", },
{ field = "haloExp",		value = "int",		desc = "精华经验", },
{ field = "useLogic",		value = "string",		desc = "物品使用", },
{ field = "useType",		value = "int",		desc = "可否背包使用", },
{ field = "sortId",		value = "int",		desc = "符文排序", },
)

({ type = "runeExp",		file = "rune.xls",		sheet= "精华升级经验", },
{ index = "star",		value = "int",		desc = "精华星级", },
{ field = "lv",		value = "int",		desc = "精华等级", },
{ field = "exp",		value = "int",		desc = "升级所需经验", },
{ field = "kuang",		value = "int",		desc = "底框", },
)

({ type = "servant",		file = "servant.xls",		sheet= "从者", },
{ index = "id",		value = "int",		desc = "ID", },
{ field = "name",		value = "string",		desc = "名称", },
{ field = "openLv",		value = "int",		desc = "开放等级", },
{ field = "maxLv",		value = "int",		desc = "最大等级", },
{ field = "maxAttrValues",		value = "string",		desc = "属性最大值", },
{ field = "icon",		value = "string",		desc = "容器头像", },
{ field = "img",		value = "string",		desc = "卡牌形象", },
{ field = "effectId",		value = "string",		desc = "出场特效", },
{ field = "icon2",		value = "string",		desc = "摁钮头像", },
{ field = "cdTime",		value = "int",		desc = "CD时间", },
)

({ type = "servant_exp",		file = "servant.xls",		sheet= "升级", },
{ index = "level",		value = "int",		desc = "等级", },
{ field = "upgradeStuffs",		value = "string",		desc = "升到当前等级所需材料", },
{ field = "upgradeMoney",		value = "int",		desc = "升到当前等级所需金币", },
)

({ type = "skills",		file = "skills.xls",		sheet= "技能表", },
{ index = "id",		value = "int",		desc = "技能ID(100开始）", },
{ field = "name",		value = "string",		desc = "技能名", },
{ field = "remark",		value = "string",		desc = "技能描述", },
{ field = "openStar",		value = "int",		desc = "开放星级", },
{ field = "filterVs",		value = "string",		desc = "选人", },
{ field = "sys",		value = "int",		desc = "系统", },
{ field = "openStrength",		value = "int",		desc = "技能学习品阶限制", },
{ field = "isAim",		value = "int",		desc = "目标", },
{ field = "tagert",		value = "int",		desc = "增减益", },
{ field = "isStop",		value = "int",		desc = "能否被打断", },
{ field = "isHideEffect",		value = "int",		desc = "是否隐藏特效", },
{ field = "distance",		value = "int",		desc = "释放距离象素", },
{ field = "logicType",		value = "int",		desc = "技能逻辑类型", },
{ field = "buffId",		value = "string",		desc = "状态ID", },
{ field = "skillBefore",		value = "string",		desc = "技能前奏", },
{ field = "pkBefore",		value = "string",		desc = "pk前运行,只运行释放者", },
{ field = "beforeEvn",		value = "string",		desc = "技能释放前的逻辑", },
{ field = "endEvn",		value = "string",		desc = "技能释放完后的逻辑", },
{ field = "pkEnd",		value = "string",		desc = "pk结束后运行,只运行释放者", },
{ field = "spellable",		value = "int",		desc = "状态下允许被控制中施放", },
{ field = "attackStyle",		value = "int",		desc = "攻击方式", },
{ field = "typeId",		value = "int",		desc = "技能大类id", },
{ field = "lv",		value = "int",		desc = "技能等级", },
{ field = "skillType",		value = "int",		desc = "技能类型", },
{ field = "coldDown",		value = "int",		desc = "冷却时间", },
{ field = "mpCost",		value = "int",		desc = "消耗MP", },
{ field = "icon",		value = "int",		desc = "技能图标", },
{ field = "aniId",		value = "int",		desc = "技能动画", },
{ field = "lvId",		value = "int",		desc = "层", },
{ field = "point",		value = "int",		desc = "点数", },
{ field = "maxPoint",		value = "int",		desc = "最多点数", },
{ field = "hero",		value = "int",		desc = "技能所属英雄", },
{ field = "moneyCost",		value = "int",		desc = "消耗的金钱", },
{ field = "music",		value = "string",		desc = "技能释放音效", },
{ field = "bulletMusic",		value = "string",		desc = "子弹击中音效", },
{ field = "phyHurtVal",		value = "string",		desc = "物理伤害", },
{ field = "magHurtVal",		value = "string",		desc = "魔法伤害", },
{ field = "critrate",		value = "string",		desc = "附加暴击", },
)

({ type = "skin",		file = "skin.xls",		sheet= "皮肤", },
{ index = "skinId",		value = "int",		desc = "卡牌ID编号", },
{ field = "animationIdSub",		value = "int",		desc = "角色资源ID", },
{ field = "photoIdSub",		value = "int",		desc = "背包头像ID", },
{ field = "spineId2Sub",		value = "string",		desc = "图鉴动画", },
{ field = "fightIconSub",		value = "int",		desc = "战斗头像", },
{ field = "heroTpId",		value = "string",		desc = "适用英雄", },
{ field = "buffTpId",		value = "int",		desc = "增益buff", },
{ field = "returnItem",		value = "string",		desc = "返还的道具", },
)

({ type = "strengthenCost",		file = "exp.xls",		sheet= "升阶消耗", },
{ index = "star",		value = "int",		desc = "星星", },
{ field = "strengthen",		value = "int",		desc = "阶数", },
{ field = "heroStrenCost",		value = "int",		desc = "英雄升阶金币", },
{ field = "equipStrenCost",		value = "int",		desc = "装备升阶金币", },
{ field = "upgradeStrengthNeedExp",		value = "int",		desc = "升阶经验", },
{ field = "upgradeStrengthProvideExp",		value = "int",		desc = "被吃经验值", },
)

({ type = "text",		file = "text.xls",		sheet= "UI", },
{ index = "en",		value = "string",		desc = "string", },
{ field = "CN",		value = "string",		desc = "string", },
)

({ type = "tong_guanghuan",		file = "tong.xls",		sheet= "公会光环", },
{ index = "lv",		value = "int",		desc = "等级", },
{ field = "reqTongLv",		value = "int",		desc = "所需联盟等级", },
{ field = "lvUpExp",		value = "int",		desc = "升级所需经验", },
{ field = "hpUp",		value = "int",		desc = "HP加成", },
{ field = "phyAttackUp",		value = "int",		desc = "物攻加成", },
{ field = "mpAttackUp",		value = "int",		desc = "法攻加成", },
)

({ type = "upstarCost",		file = "exp.xls",		sheet= "星级数值", },
{ index = "star",		value = "int",		desc = "星星", },
{ field = "heroUpstarCost",		value = "int",		desc = "英雄材料升星消耗金币", },
{ field = "heroRebuildCost",		value = "int",		desc = "英雄熔炉升星消耗金币", },
{ field = "equipRebuildCost",		value = "int",		desc = "装备熔炉升星消耗金币", },
{ field = "itemRebuildCost",		value = "int",		desc = "材料熔炉升星消耗金币", },
{ field = "equipOrienCost",		value = "int",		desc = "材料必出套装消耗钻石", },
{ field = "upgradeHeroStrengthExp",		value = "int",		desc = "狗粮增加的经验", },
)

({ type = "vip",		file = "vip.xls",		sheet= "VIP", },
{ index = "vipLv",		value = "int",		desc = "等级", },
{ field = "upgradeExp",		value = "int",		desc = "升级所需vip经验", },
{ field = "powerContent",		value = "string",		desc = "特权功能说明", },
{ field = "powerGift",		value = "string",		desc = "特权礼包", },
{ field = "vipBagPrice",		value = "int",		desc = "vip礼包价格", },
)

({ type = "yxdt",		file = "yxdt.xls",		sheet= "修炼加成", },
{ index = "id",		value = "int",		desc = "英雄id", },
{ field = "difficulty",		value = "int",		desc = "难度", },
{ field = "guanId",		value = "int",		desc = "关卡Id", },
{ field = "lv",		value = "int",		desc = "开放等级", },
{ field = "gsPoint",		value = "int",		desc = "推荐战力", },
{ field = "awards",		value = "string",		desc = "奖励", },
{ field = "resetConsume",		value = "string",		desc = "重置消耗", },
)

