-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('HallData_pb')


local PLAYTYPE = protobuf.EnumDescriptor();
local PLAYTYPE_GOLD_ENUM = protobuf.EnumValueDescriptor();
local PLAYTYPE_CARD_ENUM = protobuf.EnumValueDescriptor();
local PLAYDATA = protobuf.Descriptor();
local PLAYDATA_PLAYTYPE_FIELD = protobuf.FieldDescriptor();
local PLAYDATA_GOLDDATA_FIELD = protobuf.FieldDescriptor();
local PLAYDATA_CARDDATA_FIELD = protobuf.FieldDescriptor();
local GOLDDATA = protobuf.Descriptor();
local GOLDDATA_TYPEID_FIELD = protobuf.FieldDescriptor();
local GOLDDATA_NAME_FIELD = protobuf.FieldDescriptor();
local GOLDDATA_ISOPEN_FIELD = protobuf.FieldDescriptor();
local GOLDDATA_ITEMNAME_FIELD = protobuf.FieldDescriptor();
local GOLDDATA_SORT_FIELD = protobuf.FieldDescriptor();
local CARDDATA = protobuf.Descriptor();
local CARDDATA_TYPEID_FIELD = protobuf.FieldDescriptor();
local CARDDATA_NAME_FIELD = protobuf.FieldDescriptor();
local CARDDATA_ISOPEN_FIELD = protobuf.FieldDescriptor();
local CARDDATA_ITEMNAME_FIELD = protobuf.FieldDescriptor();
local CARDDATA_SORT_FIELD = protobuf.FieldDescriptor();
local HALLDATARESPONSE = protobuf.Descriptor();
local HALLDATARESPONSE_PLAYDATAS_FIELD = protobuf.FieldDescriptor();

PLAYTYPE_GOLD_ENUM.name = "Gold"
PLAYTYPE_GOLD_ENUM.index = 0
PLAYTYPE_GOLD_ENUM.number = 1
PLAYTYPE_CARD_ENUM.name = "Card"
PLAYTYPE_CARD_ENUM.index = 1
PLAYTYPE_CARD_ENUM.number = 2
PLAYTYPE.name = "PlayType"
PLAYTYPE.full_name = ".PlayType"
PLAYTYPE.values = {PLAYTYPE_GOLD_ENUM,PLAYTYPE_CARD_ENUM}
PLAYDATA_PLAYTYPE_FIELD.name = "playType"
PLAYDATA_PLAYTYPE_FIELD.full_name = ".PlayData.playType"
PLAYDATA_PLAYTYPE_FIELD.number = 1
PLAYDATA_PLAYTYPE_FIELD.index = 0
PLAYDATA_PLAYTYPE_FIELD.label = 2
PLAYDATA_PLAYTYPE_FIELD.has_default_value = false
PLAYDATA_PLAYTYPE_FIELD.default_value = nil
PLAYDATA_PLAYTYPE_FIELD.enum_type = PLAYTYPE
PLAYDATA_PLAYTYPE_FIELD.type = 14
PLAYDATA_PLAYTYPE_FIELD.cpp_type = 8

PLAYDATA_GOLDDATA_FIELD.name = "goldData"
PLAYDATA_GOLDDATA_FIELD.full_name = ".PlayData.goldData"
PLAYDATA_GOLDDATA_FIELD.number = 2
PLAYDATA_GOLDDATA_FIELD.index = 1
PLAYDATA_GOLDDATA_FIELD.label = 1
PLAYDATA_GOLDDATA_FIELD.has_default_value = false
PLAYDATA_GOLDDATA_FIELD.default_value = nil
PLAYDATA_GOLDDATA_FIELD.message_type = GOLDDATA
PLAYDATA_GOLDDATA_FIELD.type = 11
PLAYDATA_GOLDDATA_FIELD.cpp_type = 10

PLAYDATA_CARDDATA_FIELD.name = "cardData"
PLAYDATA_CARDDATA_FIELD.full_name = ".PlayData.cardData"
PLAYDATA_CARDDATA_FIELD.number = 3
PLAYDATA_CARDDATA_FIELD.index = 2
PLAYDATA_CARDDATA_FIELD.label = 1
PLAYDATA_CARDDATA_FIELD.has_default_value = false
PLAYDATA_CARDDATA_FIELD.default_value = nil
PLAYDATA_CARDDATA_FIELD.message_type = CARDDATA
PLAYDATA_CARDDATA_FIELD.type = 11
PLAYDATA_CARDDATA_FIELD.cpp_type = 10

PLAYDATA.name = "PlayData"
PLAYDATA.full_name = ".PlayData"
PLAYDATA.nested_types = {}
PLAYDATA.enum_types = {}
PLAYDATA.fields = {PLAYDATA_PLAYTYPE_FIELD, PLAYDATA_GOLDDATA_FIELD, PLAYDATA_CARDDATA_FIELD}
PLAYDATA.is_extendable = false
PLAYDATA.extensions = {}
GOLDDATA_TYPEID_FIELD.name = "typeId"
GOLDDATA_TYPEID_FIELD.full_name = ".GoldData.typeId"
GOLDDATA_TYPEID_FIELD.number = 1
GOLDDATA_TYPEID_FIELD.index = 0
GOLDDATA_TYPEID_FIELD.label = 2
GOLDDATA_TYPEID_FIELD.has_default_value = false
GOLDDATA_TYPEID_FIELD.default_value = 0
GOLDDATA_TYPEID_FIELD.type = 5
GOLDDATA_TYPEID_FIELD.cpp_type = 1

GOLDDATA_NAME_FIELD.name = "name"
GOLDDATA_NAME_FIELD.full_name = ".GoldData.name"
GOLDDATA_NAME_FIELD.number = 2
GOLDDATA_NAME_FIELD.index = 1
GOLDDATA_NAME_FIELD.label = 2
GOLDDATA_NAME_FIELD.has_default_value = false
GOLDDATA_NAME_FIELD.default_value = ""
GOLDDATA_NAME_FIELD.type = 9
GOLDDATA_NAME_FIELD.cpp_type = 9

GOLDDATA_ISOPEN_FIELD.name = "isOpen"
GOLDDATA_ISOPEN_FIELD.full_name = ".GoldData.isOpen"
GOLDDATA_ISOPEN_FIELD.number = 3
GOLDDATA_ISOPEN_FIELD.index = 2
GOLDDATA_ISOPEN_FIELD.label = 2
GOLDDATA_ISOPEN_FIELD.has_default_value = false
GOLDDATA_ISOPEN_FIELD.default_value = false
GOLDDATA_ISOPEN_FIELD.type = 8
GOLDDATA_ISOPEN_FIELD.cpp_type = 7

GOLDDATA_ITEMNAME_FIELD.name = "itemName"
GOLDDATA_ITEMNAME_FIELD.full_name = ".GoldData.itemName"
GOLDDATA_ITEMNAME_FIELD.number = 4
GOLDDATA_ITEMNAME_FIELD.index = 3
GOLDDATA_ITEMNAME_FIELD.label = 2
GOLDDATA_ITEMNAME_FIELD.has_default_value = false
GOLDDATA_ITEMNAME_FIELD.default_value = ""
GOLDDATA_ITEMNAME_FIELD.type = 9
GOLDDATA_ITEMNAME_FIELD.cpp_type = 9

GOLDDATA_SORT_FIELD.name = "sort"
GOLDDATA_SORT_FIELD.full_name = ".GoldData.sort"
GOLDDATA_SORT_FIELD.number = 5
GOLDDATA_SORT_FIELD.index = 4
GOLDDATA_SORT_FIELD.label = 1
GOLDDATA_SORT_FIELD.has_default_value = false
GOLDDATA_SORT_FIELD.default_value = 0
GOLDDATA_SORT_FIELD.type = 5
GOLDDATA_SORT_FIELD.cpp_type = 1

GOLDDATA.name = "GoldData"
GOLDDATA.full_name = ".GoldData"
GOLDDATA.nested_types = {}
GOLDDATA.enum_types = {}
GOLDDATA.fields = {GOLDDATA_TYPEID_FIELD, GOLDDATA_NAME_FIELD, GOLDDATA_ISOPEN_FIELD, GOLDDATA_ITEMNAME_FIELD, GOLDDATA_SORT_FIELD}
GOLDDATA.is_extendable = false
GOLDDATA.extensions = {}
CARDDATA_TYPEID_FIELD.name = "typeId"
CARDDATA_TYPEID_FIELD.full_name = ".CardData.typeId"
CARDDATA_TYPEID_FIELD.number = 1
CARDDATA_TYPEID_FIELD.index = 0
CARDDATA_TYPEID_FIELD.label = 2
CARDDATA_TYPEID_FIELD.has_default_value = false
CARDDATA_TYPEID_FIELD.default_value = 0
CARDDATA_TYPEID_FIELD.type = 5
CARDDATA_TYPEID_FIELD.cpp_type = 1

CARDDATA_NAME_FIELD.name = "name"
CARDDATA_NAME_FIELD.full_name = ".CardData.name"
CARDDATA_NAME_FIELD.number = 2
CARDDATA_NAME_FIELD.index = 1
CARDDATA_NAME_FIELD.label = 2
CARDDATA_NAME_FIELD.has_default_value = false
CARDDATA_NAME_FIELD.default_value = ""
CARDDATA_NAME_FIELD.type = 9
CARDDATA_NAME_FIELD.cpp_type = 9

CARDDATA_ISOPEN_FIELD.name = "isOpen"
CARDDATA_ISOPEN_FIELD.full_name = ".CardData.isOpen"
CARDDATA_ISOPEN_FIELD.number = 3
CARDDATA_ISOPEN_FIELD.index = 2
CARDDATA_ISOPEN_FIELD.label = 2
CARDDATA_ISOPEN_FIELD.has_default_value = false
CARDDATA_ISOPEN_FIELD.default_value = false
CARDDATA_ISOPEN_FIELD.type = 8
CARDDATA_ISOPEN_FIELD.cpp_type = 7

CARDDATA_ITEMNAME_FIELD.name = "itemName"
CARDDATA_ITEMNAME_FIELD.full_name = ".CardData.itemName"
CARDDATA_ITEMNAME_FIELD.number = 4
CARDDATA_ITEMNAME_FIELD.index = 3
CARDDATA_ITEMNAME_FIELD.label = 2
CARDDATA_ITEMNAME_FIELD.has_default_value = false
CARDDATA_ITEMNAME_FIELD.default_value = ""
CARDDATA_ITEMNAME_FIELD.type = 9
CARDDATA_ITEMNAME_FIELD.cpp_type = 9

CARDDATA_SORT_FIELD.name = "sort"
CARDDATA_SORT_FIELD.full_name = ".CardData.sort"
CARDDATA_SORT_FIELD.number = 5
CARDDATA_SORT_FIELD.index = 4
CARDDATA_SORT_FIELD.label = 1
CARDDATA_SORT_FIELD.has_default_value = false
CARDDATA_SORT_FIELD.default_value = 0
CARDDATA_SORT_FIELD.type = 5
CARDDATA_SORT_FIELD.cpp_type = 1

CARDDATA.name = "CardData"
CARDDATA.full_name = ".CardData"
CARDDATA.nested_types = {}
CARDDATA.enum_types = {}
CARDDATA.fields = {CARDDATA_TYPEID_FIELD, CARDDATA_NAME_FIELD, CARDDATA_ISOPEN_FIELD, CARDDATA_ITEMNAME_FIELD, CARDDATA_SORT_FIELD}
CARDDATA.is_extendable = false
CARDDATA.extensions = {}
HALLDATARESPONSE_PLAYDATAS_FIELD.name = "playDatas"
HALLDATARESPONSE_PLAYDATAS_FIELD.full_name = ".HallDataResponse.playDatas"
HALLDATARESPONSE_PLAYDATAS_FIELD.number = 1
HALLDATARESPONSE_PLAYDATAS_FIELD.index = 0
HALLDATARESPONSE_PLAYDATAS_FIELD.label = 3
HALLDATARESPONSE_PLAYDATAS_FIELD.has_default_value = false
HALLDATARESPONSE_PLAYDATAS_FIELD.default_value = {}
HALLDATARESPONSE_PLAYDATAS_FIELD.message_type = PLAYDATA
HALLDATARESPONSE_PLAYDATAS_FIELD.type = 11
HALLDATARESPONSE_PLAYDATAS_FIELD.cpp_type = 10

HALLDATARESPONSE.name = "HallDataResponse"
HALLDATARESPONSE.full_name = ".HallDataResponse"
HALLDATARESPONSE.nested_types = {}
HALLDATARESPONSE.enum_types = {}
HALLDATARESPONSE.fields = {HALLDATARESPONSE_PLAYDATAS_FIELD}
HALLDATARESPONSE.is_extendable = false
HALLDATARESPONSE.extensions = {}

Card = 2
CardData = protobuf.Message(CARDDATA)
Gold = 1
GoldData = protobuf.Message(GOLDDATA)
HallDataResponse = protobuf.Message(HALLDATARESPONSE)
PlayData = protobuf.Message(PLAYDATA)

