-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local MSGDEF_PB = require("MsgDef_pb")
module('request_pb')


local REQUEST = protobuf.Descriptor();
local REQUEST_HEADER_FIELD = protobuf.FieldDescriptor();
local REQUEST_BODY_FIELD = protobuf.FieldDescriptor();
local REQUEST_NUM_FIELD = protobuf.FieldDescriptor();
local REQUESTHEADER = protobuf.Descriptor();
local REQUESTHEADER_COMMAND_FIELD = protobuf.FieldDescriptor();
local REQUESTHEADER_USERID_FIELD = protobuf.FieldDescriptor();
local REQUESTHEADER_TOKEN_FIELD = protobuf.FieldDescriptor();
local REQUESTHEADER_SEQID_FIELD = protobuf.FieldDescriptor();
local REQUESTBODY = protobuf.Descriptor();
local REQUESTBODY_SERIALIZED_CONTENT_FIELD = protobuf.FieldDescriptor();

REQUEST_HEADER_FIELD.name = "header"
REQUEST_HEADER_FIELD.full_name = ".Request.header"
REQUEST_HEADER_FIELD.number = 1
REQUEST_HEADER_FIELD.index = 0
REQUEST_HEADER_FIELD.label = 2
REQUEST_HEADER_FIELD.has_default_value = false
REQUEST_HEADER_FIELD.default_value = nil
REQUEST_HEADER_FIELD.message_type = REQUESTHEADER
REQUEST_HEADER_FIELD.type = 11
REQUEST_HEADER_FIELD.cpp_type = 10

REQUEST_BODY_FIELD.name = "body"
REQUEST_BODY_FIELD.full_name = ".Request.body"
REQUEST_BODY_FIELD.number = 2
REQUEST_BODY_FIELD.index = 1
REQUEST_BODY_FIELD.label = 2
REQUEST_BODY_FIELD.has_default_value = false
REQUEST_BODY_FIELD.default_value = nil
REQUEST_BODY_FIELD.message_type = REQUESTBODY
REQUEST_BODY_FIELD.type = 11
REQUEST_BODY_FIELD.cpp_type = 10

REQUEST_NUM_FIELD.name = "num"
REQUEST_NUM_FIELD.full_name = ".Request.num"
REQUEST_NUM_FIELD.number = 3
REQUEST_NUM_FIELD.index = 2
REQUEST_NUM_FIELD.label = 1
REQUEST_NUM_FIELD.has_default_value = false
REQUEST_NUM_FIELD.default_value = 0
REQUEST_NUM_FIELD.type = 5
REQUEST_NUM_FIELD.cpp_type = 1

REQUEST.name = "Request"
REQUEST.full_name = ".Request"
REQUEST.nested_types = {}
REQUEST.enum_types = {}
REQUEST.fields = {REQUEST_HEADER_FIELD, REQUEST_BODY_FIELD, REQUEST_NUM_FIELD}
REQUEST.is_extendable = false
REQUEST.extensions = {}
REQUESTHEADER_COMMAND_FIELD.name = "command"
REQUESTHEADER_COMMAND_FIELD.full_name = ".RequestHeader.command"
REQUESTHEADER_COMMAND_FIELD.number = 1
REQUESTHEADER_COMMAND_FIELD.index = 0
REQUESTHEADER_COMMAND_FIELD.label = 2
REQUESTHEADER_COMMAND_FIELD.has_default_value = false
REQUESTHEADER_COMMAND_FIELD.default_value = nil
REQUESTHEADER_COMMAND_FIELD.enum_type = MSGDEF_PB.COMMAND
REQUESTHEADER_COMMAND_FIELD.type = 14
REQUESTHEADER_COMMAND_FIELD.cpp_type = 8

REQUESTHEADER_USERID_FIELD.name = "userId"
REQUESTHEADER_USERID_FIELD.full_name = ".RequestHeader.userId"
REQUESTHEADER_USERID_FIELD.number = 2
REQUESTHEADER_USERID_FIELD.index = 1
REQUESTHEADER_USERID_FIELD.label = 1
REQUESTHEADER_USERID_FIELD.has_default_value = false
REQUESTHEADER_USERID_FIELD.default_value = ""
REQUESTHEADER_USERID_FIELD.type = 9
REQUESTHEADER_USERID_FIELD.cpp_type = 9

REQUESTHEADER_TOKEN_FIELD.name = "token"
REQUESTHEADER_TOKEN_FIELD.full_name = ".RequestHeader.token"
REQUESTHEADER_TOKEN_FIELD.number = 3
REQUESTHEADER_TOKEN_FIELD.index = 2
REQUESTHEADER_TOKEN_FIELD.label = 1
REQUESTHEADER_TOKEN_FIELD.has_default_value = false
REQUESTHEADER_TOKEN_FIELD.default_value = ""
REQUESTHEADER_TOKEN_FIELD.type = 9
REQUESTHEADER_TOKEN_FIELD.cpp_type = 9

REQUESTHEADER_SEQID_FIELD.name = "seqID"
REQUESTHEADER_SEQID_FIELD.full_name = ".RequestHeader.seqID"
REQUESTHEADER_SEQID_FIELD.number = 4
REQUESTHEADER_SEQID_FIELD.index = 3
REQUESTHEADER_SEQID_FIELD.label = 1
REQUESTHEADER_SEQID_FIELD.has_default_value = false
REQUESTHEADER_SEQID_FIELD.default_value = 0
REQUESTHEADER_SEQID_FIELD.type = 5
REQUESTHEADER_SEQID_FIELD.cpp_type = 1

REQUESTHEADER.name = "RequestHeader"
REQUESTHEADER.full_name = ".RequestHeader"
REQUESTHEADER.nested_types = {}
REQUESTHEADER.enum_types = {}
REQUESTHEADER.fields = {REQUESTHEADER_COMMAND_FIELD, REQUESTHEADER_USERID_FIELD, REQUESTHEADER_TOKEN_FIELD, REQUESTHEADER_SEQID_FIELD}
REQUESTHEADER.is_extendable = false
REQUESTHEADER.extensions = {}
REQUESTBODY_SERIALIZED_CONTENT_FIELD.name = "serialized_content"
REQUESTBODY_SERIALIZED_CONTENT_FIELD.full_name = ".RequestBody.serialized_content"
REQUESTBODY_SERIALIZED_CONTENT_FIELD.number = 1
REQUESTBODY_SERIALIZED_CONTENT_FIELD.index = 0
REQUESTBODY_SERIALIZED_CONTENT_FIELD.label = 1
REQUESTBODY_SERIALIZED_CONTENT_FIELD.has_default_value = false
REQUESTBODY_SERIALIZED_CONTENT_FIELD.default_value = ""
REQUESTBODY_SERIALIZED_CONTENT_FIELD.type = 12
REQUESTBODY_SERIALIZED_CONTENT_FIELD.cpp_type = 9

REQUESTBODY.name = "RequestBody"
REQUESTBODY.full_name = ".RequestBody"
REQUESTBODY.nested_types = {}
REQUESTBODY.enum_types = {}
REQUESTBODY.fields = {REQUESTBODY_SERIALIZED_CONTENT_FIELD}
REQUESTBODY.is_extendable = false
REQUESTBODY.extensions = {}

Request = protobuf.Message(REQUEST)
RequestBody = protobuf.Message(REQUESTBODY)
RequestHeader = protobuf.Message(REQUESTHEADER)

